### ISSUE TITLE
Faltan muchos iconos

### ISSUE THREAD

**Issue by jpegea** [fabianalexisinostroza/Antu-icons#11]
Faltan muchos iconos, por ejemplo dentro de Clementine.

![issue_antu](https://user-images.githubusercontent.com/41998126/50641875-a6724480-0f69-11e9-9b3f-b1aaa9d5198c.png)

**Comment by fabianalexisinostroza** [comment]
En primer lugar, desde la misma pagina de kde store, menciono que es un tema en desarrollo y que avanzaré dependiendo del tiempo que tengo, debido a que trabajo en una escuela y recién el 5 de enero saldré de vacaciones, entonces no me dedico a esto de forma completa; por eso las demoras en que el tema no tiene todos los iconos, por eso además usa breve como tema complementario de momento se va completando el resto.

Ya durante este mes espero actualizar de forma más constante el tema.

**Comment by jpegea** [comment]
Ok. Muchas gracias por responder y enhorabuena por el gran trabajo que estás haciendo. Me gustan mucho tus iconos y espero ver como evoluciona este proyecto en los próximos tiempos apoyándolo siempre todo lo posible en su desarrollo. Saludos
