### ISSUE TITLE
[Feature Request] Different default folder colours

### ISSUE THREAD

**Issue by RaeshaFox** [fabianalexisinostroza/Antu-icons#12]
I noticed in the icon pack there are different folder colours available, including black. However, there are no variants of these for the other folder icons, such as images or projects folder icons.
I'd love to see different versions of Antu using different colours for the default folder theme system-wide. I'd personally like to see a black theme.
Would this be possible?

**Comment by fabianalexisinostroza** [comment]
Hi ! It's a possibility, not immediately now but in the future releases I will add support for multiple folder color icons. (: greetings
