### ISSUE TITLE
Wrong icon Discover - KDE Neon 5.12

### ISSUE THREAD

**Issue by x11tete11x** [fabianalexisinostroza/Antu-icons#2]
Hi guys!, looks like Antu (i installed Antu from git) it's picking the wrong icon for Discover

![imagen](https://user-images.githubusercontent.com/2127236/39768652-590eb608-52c0-11e8-8711-a40213a8668c.png)

**Comment by fabianalexisinostroza** [comment]
The icons will be on the next update 👍🏼

**Comment by fabianalexisinostroza** [comment]
Fixed discover icon.

![screenshot_20190217_202721](https://user-images.githubusercontent.com/14989730/52921124-76e98280-32f2-11e9-9805-3f117e7489fe.png)
