### ISSUE TITLE
Wrong icon Dropbox - KDE Neon 5.12

### ISSUE THREAD

**Issue by x11tete11x** [fabianalexisinostroza/Antu-icons#3]
Hi guys!, looks like Antu (i installed Antu from git) it's picking the wrong icon for Dropbox

![imagen](https://user-images.githubusercontent.com/2127236/39768693-77bba066-52c0-11e8-8688-ef81833fa89c.png)

**Comment by fabianalexisinostroza** [comment]
The icons will be on the next update 👍🏼
