### ISSUE TITLE
No Dropbox icon for folder

### ISSUE THREAD

**Issue by trbjo** [fabianalexisinostroza/Antu-icons#4]
Hi, very good looking icon theme, especially the folders. What I am missing from the theme is a Dropbox icon. Currently my Dolphin file manager looks like this:  
![skaermbillede 2018-08-07 kl 21 04-1](https://user-images.githubusercontent.com/26080212/43796782-7e97a2d8-9a85-11e8-9b04-62a9ea1e2474.png)

Can you add an icon for the Dropbox directory?

**Comment by fabianalexisinostroza** [comment]
Yes, for the next realease a Dropbox Folder will be include

**Comment by trbjo** [comment]
Can you send me the (Inkscape?) template you use for folders? I might try to make the icon myself.

**Comment by fabianalexisinostroza** [comment]
The icon will be added today at 21:00 (Chile) ;)

**Comment by fabianalexisinostroza** [comment]
Folder icons added to Antü

![screenshot_20180808_211224](https://user-images.githubusercontent.com/14989730/43872746-37d7cfe0-9b51-11e8-8a73-7e2a8ce9ee2a.png)

![screenshot_20180808_212138](https://user-images.githubusercontent.com/14989730/43872737-2b25ad12-9b51-11e8-9459-cee1f770dbbf.png)
