### ISSUE TITLE
A laundry list of icon requests

### ISSUE THREAD

**Issue by fusion809** [fabianalexisinostroza/Antu-icons#5]
Hi,

This is one of only three icon themes I presently like that are complete enough for me to be able to use them fairly seamlessly under KDE Plasma. There are exception applications with icons not in this theme that appear as empty icons under KDE Plasma. Here are some:

* [Atom](https://atom.io), including the beta, dev, nightly and stable channels (icon names: [`atom-beta`](https://raw.githubusercontent.com/atom/atom/master/resources/app-icons/beta/atom.ico), [`atom-dev`](https://raw.githubusercontent.com/atom/atom/master/resources/app-icons/dev/atom.ico), [`atom-nightly`](https://raw.githubusercontent.com/atom/atom/master/resources/app-icons/nightly/atom.ico) and [`atom`](https://raw.githubusercontent.com/atom/atom/master/resources/app-icons/stable/atom.ico), respectively)
* [Authy](https://authy.com/) (icon name: [`authy`](https://lh3.googleusercontent.com/bmv9somUcw2qxzn5BY6O0x5ORq8oPOTFm5kZssdmlenVSpKTF-s5Bre6XgezeauBfKkxzIx5ttI=w50-h50-e365) & `chrome-gaedmjdfmmahhbjefcbgaolhhanlaolb-default`)
* [Avogadro](http://avogadro.cc/) (icon name [`avogadro`](https://raw.githubusercontent.com/cryos/avogadro/master/avogadro/src/icons/avogadro.png))
* [Avogadro2](https://www.openchemistry.org/projects/avogadro2/) (icon name: [`avogadro2`](https://www.openchemistry.org/wp-content/uploads/2014/04/Avogadro2_256.png))
* [Google Earth Pro](https://www.google.com/earth/desktop/) (icon name: [`google-earth-pro`](https://user-images.githubusercontent.com/4717341/43995265-2c5bf700-9dee-11e8-80ea-a60a4ff3dbbc.png))
* [Jmol](http://jmol.sourceforge.net/) (icon name: [`jmol`](http://jmol.sourceforge.net/images/Jmol_icon_128.png))
* [KMahjongg](https://www.kde.org/applications/games/kmahjongg/) (icon name: [`kmahjongg`](https://www.kde.org/images/icons/kmahjongg_48.png))
* [KMines](https://www.kde.org/applications/games/kmines/) (icon name: [`kmines`](https://www.kde.org/images/icons/kmines_48.png))
* [KPatience](https://www.kde.org/applications/games/kpatience) (icon name: [`kpat`](https://www.kde.org/images/icons/kpatience_48.png))
* [MarvinSketch](https://chemaxon.com/products/marvin) (icon name: [`MarvinSketch`](https://user-images.githubusercontent.com/4717341/43995616-885335fe-9df4-11e8-9817-429cc327bf38.png))
* [MarvinView](https://chemaxon.com/products/marvin) (icon name: [`MarvinView`](https://user-images.githubusercontent.com/4717341/43995618-97121632-9df4-11e8-844c-f2a983b92e48.png))
* [NetBeans](https://netbeans.apache.org/) (icon name: [`netbeans`](https://cwiki.apache.org/confluence/download/attachments/67635710/apache-netbeans.svg), or [`apache-netbeans`](https://cwiki.apache.org/confluence/download/attachments/67635710/apache-netbeans.svg) (as of version 9.0))
* [OpenRA](https://openra.net) bundled, stable mods, namely Dune 2000 (icon name: [`openra-d2k`](https://github.com/OpenRA/OpenRA/raw/master/packaging/linux/hicolor/128x128/apps/openra-d2k.png)), Red Alert (icon name: [`openra-ra`](https://github.com/OpenRA/OpenRA/raw/master/packaging/linux/hicolor/scalable/apps/openra-d2k.svg)) and Tiberian Dawn (icon name: [`openra-cnc`](https://github.com/OpenRA/OpenRA/raw/master/packaging/linux/hicolor/scalable/apps/openra-cnc.png)).
* [PyMOL](https://pymol.org) (icon name: [`pymol`](https://upload.wikimedia.org/wikipedia/commons/8/87/PyMOL_logo.svg))
* [RuneScape NXT Client](https://www.runescape.com) (icon name: [`runescape-launcher`](https://user-images.githubusercontent.com/4717341/43995757-c90f963e-9df7-11e8-99ad-ce814cf0dda6.png))
* [Steam](https://store.steampowered.com) (icon name: [`steam`](https://user-images.githubusercontent.com/4717341/43995800-eae2a17e-9df8-11e8-89fb-5a51f35f9f58.png))

**Comment by fabianalexisinostroza** [comment]
Hi! thanks for comment. These icons will be added to my TO-DO list (: stay tuned for the updates (;
