### ISSUE TITLE
[REQUEST] Bring back toolbar icons of 0.4

### ISSUE THREAD

**Issue by otavioschwanck** [fabianalexisinostroza/Antu-icons#6]
![screenshot_20180910_212706](https://user-images.githubusercontent.com/9551316/45331303-4bdb5580-b540-11e8-8cb4-4ca317e95304.png)
I'm still using 0.4 only because of this.  Its possible to have updated version with this toolbar actions icons?

Love your work, best icon theme ever <3

**Comment by fabianalexisinostroza** [comment]
Hi!, you can still using the breeze action icons with updated Antü icons. Only you need delete all icons on "actions" folder. Only delete the monochrome icons. Antü uses Breeze (the toolbar icons on the screenshot) as fallback theme. Thanks for using my icons !!

**Comment by otavioschwanck** [comment]
Thanks! works perfectly

**Comment by fabianalexisinostroza** [comment]
Nice 😀
