### ISSUE TITLE
New Icons if possible

### ISSUE THREAD

**Issue by meowmeowxw** [fabianalexisinostroza/Antu-icons#8]
Hi,
Your icons are awesome but I would like to have the icon theme for these programs:
Visual Studio Code (name:code)
Wireshark (name:wireshark)
Geany (name: geany)
GNS3 (name: gns3)
Geogebra (name:geogebra-classic)
Thunderbird (name: thunderbird)

**Comment by fabianalexisinostroza** [comment]
Hi ! thanks for the comment. New icons coming soon, maybe this Sunday antü will have an update (: Stay tuned

**Comment by meowmeowxw** [comment]
Thank you !!

**Comment by meowmeowxw** [comment]
Hi, I saw that you've done a new icon theme,
are the Antu Icons no longer supported ?
or are you going to maintain both antu and kuyen icons?

**Comment by fabianalexisinostroza** [comment]
Antü icon Theme is supported, Küyen is the same icon Theme with flat colors, when Antü updates Küyen Will update too
